// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"fx-web/internal/ent/predicate"
	"fx-web/internal/ent/psconfig"
	"fx-web/internal/ent/psstrategy"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PsConfigQuery is the builder for querying PsConfig entities.
type PsConfigQuery struct {
	config
	ctx          *QueryContext
	order        []psconfig.OrderOption
	inters       []Interceptor
	predicates   []predicate.PsConfig
	withStrategy *PsStrategyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PsConfigQuery builder.
func (pcq *PsConfigQuery) Where(ps ...predicate.PsConfig) *PsConfigQuery {
	pcq.predicates = append(pcq.predicates, ps...)
	return pcq
}

// Limit the number of records to be returned by this query.
func (pcq *PsConfigQuery) Limit(limit int) *PsConfigQuery {
	pcq.ctx.Limit = &limit
	return pcq
}

// Offset to start from.
func (pcq *PsConfigQuery) Offset(offset int) *PsConfigQuery {
	pcq.ctx.Offset = &offset
	return pcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcq *PsConfigQuery) Unique(unique bool) *PsConfigQuery {
	pcq.ctx.Unique = &unique
	return pcq
}

// Order specifies how the records should be ordered.
func (pcq *PsConfigQuery) Order(o ...psconfig.OrderOption) *PsConfigQuery {
	pcq.order = append(pcq.order, o...)
	return pcq
}

// QueryStrategy chains the current query on the "strategy" edge.
func (pcq *PsConfigQuery) QueryStrategy() *PsStrategyQuery {
	query := (&PsStrategyClient{config: pcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(psconfig.Table, psconfig.FieldID, selector),
			sqlgraph.To(psstrategy.Table, psstrategy.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, psconfig.StrategyTable, psconfig.StrategyColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PsConfig entity from the query.
// Returns a *NotFoundError when no PsConfig was found.
func (pcq *PsConfigQuery) First(ctx context.Context) (*PsConfig, error) {
	nodes, err := pcq.Limit(1).All(setContextOp(ctx, pcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{psconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcq *PsConfigQuery) FirstX(ctx context.Context) *PsConfig {
	node, err := pcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PsConfig ID from the query.
// Returns a *NotFoundError when no PsConfig ID was found.
func (pcq *PsConfigQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = pcq.Limit(1).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{psconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcq *PsConfigQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := pcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PsConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PsConfig entity is found.
// Returns a *NotFoundError when no PsConfig entities are found.
func (pcq *PsConfigQuery) Only(ctx context.Context) (*PsConfig, error) {
	nodes, err := pcq.Limit(2).All(setContextOp(ctx, pcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{psconfig.Label}
	default:
		return nil, &NotSingularError{psconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcq *PsConfigQuery) OnlyX(ctx context.Context) *PsConfig {
	node, err := pcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PsConfig ID in the query.
// Returns a *NotSingularError when more than one PsConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcq *PsConfigQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = pcq.Limit(2).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{psconfig.Label}
	default:
		err = &NotSingularError{psconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcq *PsConfigQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := pcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PsConfigs.
func (pcq *PsConfigQuery) All(ctx context.Context) ([]*PsConfig, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryAll)
	if err := pcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PsConfig, *PsConfigQuery]()
	return withInterceptors[[]*PsConfig](ctx, pcq, qr, pcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pcq *PsConfigQuery) AllX(ctx context.Context) []*PsConfig {
	nodes, err := pcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PsConfig IDs.
func (pcq *PsConfigQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if pcq.ctx.Unique == nil && pcq.path != nil {
		pcq.Unique(true)
	}
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryIDs)
	if err = pcq.Select(psconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcq *PsConfigQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := pcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcq *PsConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryCount)
	if err := pcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pcq, querierCount[*PsConfigQuery](), pcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pcq *PsConfigQuery) CountX(ctx context.Context) int {
	count, err := pcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcq *PsConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryExist)
	switch _, err := pcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pcq *PsConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := pcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PsConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcq *PsConfigQuery) Clone() *PsConfigQuery {
	if pcq == nil {
		return nil
	}
	return &PsConfigQuery{
		config:       pcq.config,
		ctx:          pcq.ctx.Clone(),
		order:        append([]psconfig.OrderOption{}, pcq.order...),
		inters:       append([]Interceptor{}, pcq.inters...),
		predicates:   append([]predicate.PsConfig{}, pcq.predicates...),
		withStrategy: pcq.withStrategy.Clone(),
		// clone intermediate query.
		sql:  pcq.sql.Clone(),
		path: pcq.path,
	}
}

// WithStrategy tells the query-builder to eager-load the nodes that are connected to
// the "strategy" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *PsConfigQuery) WithStrategy(opts ...func(*PsStrategyQuery)) *PsConfigQuery {
	query := (&PsStrategyClient{config: pcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pcq.withStrategy = query
	return pcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PsConfig.Query().
//		GroupBy(psconfig.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pcq *PsConfigQuery) GroupBy(field string, fields ...string) *PsConfigGroupBy {
	pcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PsConfigGroupBy{build: pcq}
	grbuild.flds = &pcq.ctx.Fields
	grbuild.label = psconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PsConfig.Query().
//		Select(psconfig.FieldCreatedAt).
//		Scan(ctx, &v)
func (pcq *PsConfigQuery) Select(fields ...string) *PsConfigSelect {
	pcq.ctx.Fields = append(pcq.ctx.Fields, fields...)
	sbuild := &PsConfigSelect{PsConfigQuery: pcq}
	sbuild.label = psconfig.Label
	sbuild.flds, sbuild.scan = &pcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PsConfigSelect configured with the given aggregations.
func (pcq *PsConfigQuery) Aggregate(fns ...AggregateFunc) *PsConfigSelect {
	return pcq.Select().Aggregate(fns...)
}

func (pcq *PsConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pcq); err != nil {
				return err
			}
		}
	}
	for _, f := range pcq.ctx.Fields {
		if !psconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcq.path != nil {
		prev, err := pcq.path(ctx)
		if err != nil {
			return err
		}
		pcq.sql = prev
	}
	return nil
}

func (pcq *PsConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PsConfig, error) {
	var (
		nodes       = []*PsConfig{}
		_spec       = pcq.querySpec()
		loadedTypes = [1]bool{
			pcq.withStrategy != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PsConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PsConfig{config: pcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pcq.withStrategy; query != nil {
		if err := pcq.loadStrategy(ctx, query, nodes, nil,
			func(n *PsConfig, e *PsStrategy) { n.Edges.Strategy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pcq *PsConfigQuery) loadStrategy(ctx context.Context, query *PsStrategyQuery, nodes []*PsConfig, init func(*PsConfig), assign func(*PsConfig, *PsStrategy)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*PsConfig)
	for i := range nodes {
		if nodes[i].PsStrategy == nil {
			continue
		}
		fk := *nodes[i].PsStrategy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(psstrategy.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ps_strategy" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pcq *PsConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcq.querySpec()
	_spec.Node.Columns = pcq.ctx.Fields
	if len(pcq.ctx.Fields) > 0 {
		_spec.Unique = pcq.ctx.Unique != nil && *pcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pcq.driver, _spec)
}

func (pcq *PsConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(psconfig.Table, psconfig.Columns, sqlgraph.NewFieldSpec(psconfig.FieldID, field.TypeUint64))
	_spec.From = pcq.sql
	if unique := pcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pcq.path != nil {
		_spec.Unique = true
	}
	if fields := pcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, psconfig.FieldID)
		for i := range fields {
			if fields[i] != psconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pcq.withStrategy != nil {
			_spec.Node.AddColumnOnce(psconfig.FieldPsStrategy)
		}
	}
	if ps := pcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcq *PsConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcq.driver.Dialect())
	t1 := builder.Table(psconfig.Table)
	columns := pcq.ctx.Fields
	if len(columns) == 0 {
		columns = psconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcq.sql != nil {
		selector = pcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcq.ctx.Unique != nil && *pcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pcq.predicates {
		p(selector)
	}
	for _, p := range pcq.order {
		p(selector)
	}
	if offset := pcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PsConfigGroupBy is the group-by builder for PsConfig entities.
type PsConfigGroupBy struct {
	selector
	build *PsConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcgb *PsConfigGroupBy) Aggregate(fns ...AggregateFunc) *PsConfigGroupBy {
	pcgb.fns = append(pcgb.fns, fns...)
	return pcgb
}

// Scan applies the selector query and scans the result into the given value.
func (pcgb *PsConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcgb.build.ctx, ent.OpQueryGroupBy)
	if err := pcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PsConfigQuery, *PsConfigGroupBy](ctx, pcgb.build, pcgb, pcgb.build.inters, v)
}

func (pcgb *PsConfigGroupBy) sqlScan(ctx context.Context, root *PsConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pcgb.fns))
	for _, fn := range pcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pcgb.flds)+len(pcgb.fns))
		for _, f := range *pcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PsConfigSelect is the builder for selecting fields of PsConfig entities.
type PsConfigSelect struct {
	*PsConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pcs *PsConfigSelect) Aggregate(fns ...AggregateFunc) *PsConfigSelect {
	pcs.fns = append(pcs.fns, fns...)
	return pcs
}

// Scan applies the selector query and scans the result into the given value.
func (pcs *PsConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcs.ctx, ent.OpQuerySelect)
	if err := pcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PsConfigQuery, *PsConfigSelect](ctx, pcs.PsConfigQuery, pcs, pcs.inters, v)
}

func (pcs *PsConfigSelect) sqlScan(ctx context.Context, root *PsConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pcs.fns))
	for _, fn := range pcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
