// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fx-web/internal/ent/predicate"
	"fx-web/internal/ent/psstrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PsStrategyDelete is the builder for deleting a PsStrategy entity.
type PsStrategyDelete struct {
	config
	hooks    []Hook
	mutation *PsStrategyMutation
}

// Where appends a list predicates to the PsStrategyDelete builder.
func (psd *PsStrategyDelete) Where(ps ...predicate.PsStrategy) *PsStrategyDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PsStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PsStrategyDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PsStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(psstrategy.Table, sqlgraph.NewFieldSpec(psstrategy.FieldID, field.TypeUint64))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PsStrategyDeleteOne is the builder for deleting a single PsStrategy entity.
type PsStrategyDeleteOne struct {
	psd *PsStrategyDelete
}

// Where appends a list predicates to the PsStrategyDelete builder.
func (psdo *PsStrategyDeleteOne) Where(ps ...predicate.PsStrategy) *PsStrategyDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PsStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{psstrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PsStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
