// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"fx-web/internal/ent/predicate"
	"fx-web/internal/ent/psstrategy"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PsStrategyQuery is the builder for querying PsStrategy entities.
type PsStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []psstrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.PsStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PsStrategyQuery builder.
func (psq *PsStrategyQuery) Where(ps ...predicate.PsStrategy) *PsStrategyQuery {
	psq.predicates = append(psq.predicates, ps...)
	return psq
}

// Limit the number of records to be returned by this query.
func (psq *PsStrategyQuery) Limit(limit int) *PsStrategyQuery {
	psq.ctx.Limit = &limit
	return psq
}

// Offset to start from.
func (psq *PsStrategyQuery) Offset(offset int) *PsStrategyQuery {
	psq.ctx.Offset = &offset
	return psq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (psq *PsStrategyQuery) Unique(unique bool) *PsStrategyQuery {
	psq.ctx.Unique = &unique
	return psq
}

// Order specifies how the records should be ordered.
func (psq *PsStrategyQuery) Order(o ...psstrategy.OrderOption) *PsStrategyQuery {
	psq.order = append(psq.order, o...)
	return psq
}

// First returns the first PsStrategy entity from the query.
// Returns a *NotFoundError when no PsStrategy was found.
func (psq *PsStrategyQuery) First(ctx context.Context) (*PsStrategy, error) {
	nodes, err := psq.Limit(1).All(setContextOp(ctx, psq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{psstrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (psq *PsStrategyQuery) FirstX(ctx context.Context) *PsStrategy {
	node, err := psq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PsStrategy ID from the query.
// Returns a *NotFoundError when no PsStrategy ID was found.
func (psq *PsStrategyQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = psq.Limit(1).IDs(setContextOp(ctx, psq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{psstrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (psq *PsStrategyQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := psq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PsStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PsStrategy entity is found.
// Returns a *NotFoundError when no PsStrategy entities are found.
func (psq *PsStrategyQuery) Only(ctx context.Context) (*PsStrategy, error) {
	nodes, err := psq.Limit(2).All(setContextOp(ctx, psq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{psstrategy.Label}
	default:
		return nil, &NotSingularError{psstrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (psq *PsStrategyQuery) OnlyX(ctx context.Context) *PsStrategy {
	node, err := psq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PsStrategy ID in the query.
// Returns a *NotSingularError when more than one PsStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (psq *PsStrategyQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = psq.Limit(2).IDs(setContextOp(ctx, psq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{psstrategy.Label}
	default:
		err = &NotSingularError{psstrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (psq *PsStrategyQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := psq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PsStrategies.
func (psq *PsStrategyQuery) All(ctx context.Context) ([]*PsStrategy, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryAll)
	if err := psq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PsStrategy, *PsStrategyQuery]()
	return withInterceptors[[]*PsStrategy](ctx, psq, qr, psq.inters)
}

// AllX is like All, but panics if an error occurs.
func (psq *PsStrategyQuery) AllX(ctx context.Context) []*PsStrategy {
	nodes, err := psq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PsStrategy IDs.
func (psq *PsStrategyQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if psq.ctx.Unique == nil && psq.path != nil {
		psq.Unique(true)
	}
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryIDs)
	if err = psq.Select(psstrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (psq *PsStrategyQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := psq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (psq *PsStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryCount)
	if err := psq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, psq, querierCount[*PsStrategyQuery](), psq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (psq *PsStrategyQuery) CountX(ctx context.Context) int {
	count, err := psq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (psq *PsStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryExist)
	switch _, err := psq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (psq *PsStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := psq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PsStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (psq *PsStrategyQuery) Clone() *PsStrategyQuery {
	if psq == nil {
		return nil
	}
	return &PsStrategyQuery{
		config:     psq.config,
		ctx:        psq.ctx.Clone(),
		order:      append([]psstrategy.OrderOption{}, psq.order...),
		inters:     append([]Interceptor{}, psq.inters...),
		predicates: append([]predicate.PsStrategy{}, psq.predicates...),
		// clone intermediate query.
		sql:  psq.sql.Clone(),
		path: psq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PsStrategy.Query().
//		GroupBy(psstrategy.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (psq *PsStrategyQuery) GroupBy(field string, fields ...string) *PsStrategyGroupBy {
	psq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PsStrategyGroupBy{build: psq}
	grbuild.flds = &psq.ctx.Fields
	grbuild.label = psstrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PsStrategy.Query().
//		Select(psstrategy.FieldCreatedAt).
//		Scan(ctx, &v)
func (psq *PsStrategyQuery) Select(fields ...string) *PsStrategySelect {
	psq.ctx.Fields = append(psq.ctx.Fields, fields...)
	sbuild := &PsStrategySelect{PsStrategyQuery: psq}
	sbuild.label = psstrategy.Label
	sbuild.flds, sbuild.scan = &psq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PsStrategySelect configured with the given aggregations.
func (psq *PsStrategyQuery) Aggregate(fns ...AggregateFunc) *PsStrategySelect {
	return psq.Select().Aggregate(fns...)
}

func (psq *PsStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range psq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, psq); err != nil {
				return err
			}
		}
	}
	for _, f := range psq.ctx.Fields {
		if !psstrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if psq.path != nil {
		prev, err := psq.path(ctx)
		if err != nil {
			return err
		}
		psq.sql = prev
	}
	return nil
}

func (psq *PsStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PsStrategy, error) {
	var (
		nodes = []*PsStrategy{}
		_spec = psq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PsStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PsStrategy{config: psq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, psq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (psq *PsStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := psq.querySpec()
	_spec.Node.Columns = psq.ctx.Fields
	if len(psq.ctx.Fields) > 0 {
		_spec.Unique = psq.ctx.Unique != nil && *psq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, psq.driver, _spec)
}

func (psq *PsStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(psstrategy.Table, psstrategy.Columns, sqlgraph.NewFieldSpec(psstrategy.FieldID, field.TypeUint64))
	_spec.From = psq.sql
	if unique := psq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if psq.path != nil {
		_spec.Unique = true
	}
	if fields := psq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, psstrategy.FieldID)
		for i := range fields {
			if fields[i] != psstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := psq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := psq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := psq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := psq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (psq *PsStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(psq.driver.Dialect())
	t1 := builder.Table(psstrategy.Table)
	columns := psq.ctx.Fields
	if len(columns) == 0 {
		columns = psstrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if psq.sql != nil {
		selector = psq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if psq.ctx.Unique != nil && *psq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range psq.predicates {
		p(selector)
	}
	for _, p := range psq.order {
		p(selector)
	}
	if offset := psq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := psq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PsStrategyGroupBy is the group-by builder for PsStrategy entities.
type PsStrategyGroupBy struct {
	selector
	build *PsStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (psgb *PsStrategyGroupBy) Aggregate(fns ...AggregateFunc) *PsStrategyGroupBy {
	psgb.fns = append(psgb.fns, fns...)
	return psgb
}

// Scan applies the selector query and scans the result into the given value.
func (psgb *PsStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psgb.build.ctx, ent.OpQueryGroupBy)
	if err := psgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PsStrategyQuery, *PsStrategyGroupBy](ctx, psgb.build, psgb, psgb.build.inters, v)
}

func (psgb *PsStrategyGroupBy) sqlScan(ctx context.Context, root *PsStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(psgb.fns))
	for _, fn := range psgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*psgb.flds)+len(psgb.fns))
		for _, f := range *psgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*psgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PsStrategySelect is the builder for selecting fields of PsStrategy entities.
type PsStrategySelect struct {
	*PsStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pss *PsStrategySelect) Aggregate(fns ...AggregateFunc) *PsStrategySelect {
	pss.fns = append(pss.fns, fns...)
	return pss
}

// Scan applies the selector query and scans the result into the given value.
func (pss *PsStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pss.ctx, ent.OpQuerySelect)
	if err := pss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PsStrategyQuery, *PsStrategySelect](ctx, pss.PsStrategyQuery, pss, pss.inters, v)
}

func (pss *PsStrategySelect) sqlScan(ctx context.Context, root *PsStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pss.fns))
	for _, fn := range pss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
